

name: "package-image"
run-name: "Packaging image"
on: [ push ]
jobs:
  push-to-registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
        -
          name: Check out the repository
          uses: actions/checkout@v4

        -
            name: Login to DockerHub
            uses: docker/login-action@v2
            with:
                username: "${{ secrets.DOCKERHUB_USERNAME }}"
                password: "${{ secrets.DOCKERHUB_TOKEN }}"

        -
            name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
                file: ./Dockerfile
                push: true
                context: ./src
                tags: ${{ vars.DOCKERHUB_REPOSITORY}}:${{ github.sha }},"${{ vars.DOCKERHUB_REPOSITORY}}:latest"

